/* =============================================================================
   @better-trigger/worker — middleware.
   Bearer auth (skipped when BETTER_TRIGGER_API_KEY is unset; /health always
   open; the key is compared in constant time) + a loopback-only CORS
   allowlist.

   The API is unauthenticated by default, so the browser is an entry path of its
   own: with `origin: '*'` any page the user visits could POST /api/v1/trigger
   at http://localhost:4848 and read back run payloads. Only the dashboard's own
   origins are allowed by default — http/https on localhost / 127.0.0.0/8 /
   [::1], any port (the dev vite port is not fixed) — and anything else is
   answered without the Access-Control-Allow-Origin header, which is what makes
   the browser drop the response. `--cors-origin` (env
   BETTER_TRIGGER_CORS_ORIGIN) opens that up explicitly.

   Non-browser callers (the SDK, curl) send no Origin and are untouched: CORS
   only ever decides what a *browser* hands back to a page.
   ============================================================================= */
import { Buffer } from 'node:buffer';
import { createHash, timingSafeEqual } from 'node:crypto';
import type { MiddlewareHandler } from 'hono';
import { cors } from 'hono/cors';

/** Values the security middlewares pass down the chain via the Hono context
 *  (auth → rate limit → audit all run on the same outer app, so they share
 *  one context). */
export interface AppVariables {
  /** sha256 fingerprint of the API key that authenticated this request, or
   *  null when no key is configured (or auth was skipped for /health). */
  authKeyId: string | null;
  /** Correlation id generated by the audit middleware for this request. */
  auditRequestId: string;
}

/** Origins allowed on top of loopback, from `--cors-origin`. */
let configuredOrigins: string[] = [];

/**
 * Extra allowed origins, from `--cors-origin`. Called by main.ts before
 * createApp; BETTER_TRIGGER_CORS_ORIGIN is honoured either way, so an embedded
 * createApp() that never calls this still gets the env.
 */
export function setCorsOrigins(origins: string[]): void {
  configuredOrigins = parseOriginList(origins.join(','));
}

/** Splits `a,b` / repeated flags into normalized origins ('*' passes through). */
export function parseOriginList(raw: string): string[] {
  return raw
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => (s === '*' ? s : normalizeOrigin(s) ?? s));
}

/** `http://Host:3000/path` → `http://host:3000`; null when it is not a URL. */
function normalizeOrigin(raw: string): string | null {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return null;
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return null;
  return url.origin;
}

/**
 * Loopback origins only, parsed rather than pattern-matched: `new URL` is what
 * decides where the host ends, so `http://localhost.evil.com` (host
 * localhost.evil.com) and `http://localhost@evil.com` (host evil.com) are both
 * misses instead of substring hits.
 */
function isLoopbackOrigin(raw: string): boolean {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return false; // "null" (file://, sandboxed iframe) lands here too.
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return false;
  // hostname is the host without the port; IPv6 literals keep their brackets.
  // No IPv4-mapped form here: `new URL` rewrites [::ffff:127.0.0.1] to its hex
  // spelling [::ffff:7f00:1], and no browser puts either in an Origin anyway.
  const host = url.hostname.toLowerCase();
  return (
    host === 'localhost' ||
    host === '[::1]' ||
    /^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(host)
  );
}

/**
 * Configured origins plus the env, which is read here and only here — the CLI
 * hands over `--cors-origin` alone, so listing an origin in both places cannot
 * duplicate it.
 */
function extraOrigins(): string[] {
  const fromEnv = parseOriginList(process.env.BETTER_TRIGGER_CORS_ORIGIN ?? '');
  return fromEnv.length > 0 ? [...configuredOrigins, ...fromEnv] : configuredOrigins;
}

/** The origin allowed back to the caller, or null to send no CORS header. */
export function allowedOrigin(origin: string): string | null {
  if (!origin) return null; // Same-origin GETs and non-browser clients.
  const extra = extraOrigins();
  if (extra.includes('*')) return origin;
  if (isLoopbackOrigin(origin)) return origin;
  const normalized = normalizeOrigin(origin);
  return normalized !== null && extra.includes(normalized) ? origin : null;
}

export const corsMiddleware: MiddlewareHandler = cors({
  origin: (origin) => allowedOrigin(origin),
  allowMethods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS'],
  allowHeaders: ['Authorization', 'Content-Type'],
});

/**
 * Constant-time token compare. `===` stops at the first differing byte, so the
 * time it takes tells a caller how much of the key it guessed right — feed it
 * enough requests and the key falls out one byte at a time. timingSafeEqual
 * throws when the lengths differ, hence the length check first; the length
 * itself leaks, which is the standard trade (it is not the secret).
 */
function tokenMatches(token: string, key: string): boolean {
  const a = Buffer.from(token, 'utf8');
  const b = Buffer.from(key, 'utf8');
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}

/** One configured API key, optionally expiring. */
export interface ApiKeyEntry {
  key: string;
  /** Epoch ms after which the key is refused; null = never expires. */
  expiresAt: number | null;
}

/**
 * Parse one `key[@expiry]` entry. Only the LAST '@' can separate the expiry,
 * and only when the suffix parses as a date (`2026-12-31`, or any ISO 8601
 * value `new Date` accepts) — a key that merely contains '@' (or an
 * unparseable suffix) is kept whole. An expired-but-listed key is not
 * dropped: it is rejected with a distinct reason so the audit trail shows
 * which credential was turned off.
 */
export function parseKeyEntry(raw: string): ApiKeyEntry {
  const at = raw.lastIndexOf('@');
  if (at > 0) {
    const expiry = new Date(raw.slice(at + 1));
    if (!Number.isNaN(expiry.getTime())) {
      return { key: raw.slice(0, at), expiresAt: expiry.getTime() };
    }
  }
  return { key: raw, expiresAt: null };
}

/** Every configured key: BETTER_TRIGGER_API_KEY first, then the
 *  comma-separated BETTER_TRIGGER_API_KEYS entries. Read per request, like
 *  the rest of the auth env. */
export function configuredApiKeys(env = process.env): ApiKeyEntry[] {
  const out: ApiKeyEntry[] = [];
  const primary = env.BETTER_TRIGGER_API_KEY;
  if (primary !== undefined && primary !== '') out.push(parseKeyEntry(primary));
  for (const part of (env.BETTER_TRIGGER_API_KEYS ?? '').split(',')) {
    const s = part.trim();
    if (s !== '') out.push(parseKeyEntry(s));
  }
  return out;
}

/**
 * The first entry whose key equals `token`. Every entry is compared before
 * returning (constant-time per entry), so the response time does not reveal
 * which position in the list matched — the index is not the secret, but a
 * full pass removes the question instead of arguing about it. Comparing
 * against several keys costs N timingSafeEqual calls; N is the number of
 * configured keys, which is small.
 */
export function matchApiKey(token: string, entries: readonly ApiKeyEntry[]): ApiKeyEntry | null {
  let matched: ApiKeyEntry | null = null;
  for (const entry of entries) {
    if (tokenMatches(token, entry.key)) matched = entry;
  }
  return matched;
}

/** Short sha256 fingerprint for audit lines and rate-limit buckets — enough
 *  to tell keys apart in a log, never enough to reconstruct one. */
export function keyFingerprint(key: string): string {
  return `key_${createHash('sha256').update(key).digest('hex').slice(0, 12)}`;
}

/** TCP peer address off the node IncomingMessage (@hono/node-server puts it
 *  in c.env.incoming); null for in-process fetches. Shared by the audit log's
 *  caller field and the rate limiter's keyless per-IP bucket (p2-31). */
export function remoteAddressOf(c: { env: unknown }): string | null {
  const incoming = (c.env as
    | { incoming?: { socket?: { remoteAddress?: string } } }
    | undefined)?.incoming;
  return incoming?.socket?.remoteAddress ?? null;
}

/**
 * Bearer auth against every configured key (multi-key, O6). No-op when no
 * key is configured. /api/v1/health is always open. On success the matched
 * key's fingerprint is set on the context (authKeyId) for the rate limiter
 * and the audit log. An expired key answers 401 with code `key_expired` — a
 * distinct code on purpose, so the audit log says *why* a credential stopped
 * working — while a wrong or missing key keeps the pre-existing
 * `unauthorized` shape verbatim.
 */
export function authMiddleware(): MiddlewareHandler<{ Variables: AppVariables }> {
  return async (c, next) => {
    const entries = configuredApiKeys();
    if (entries.length === 0) return next();

    const path = c.req.path;
    if (path === '/api/v1/health') return next();

    const header = c.req.header('Authorization') ?? '';
    // RFC 7235: the auth scheme is case-insensitive, so `bearer` / `BEARER`
    // must be accepted too. The token is everything after the first space,
    // taken verbatim — the key itself stays case-sensitive.
    const space = header.indexOf(' ');
    const token =
      space !== -1 && header.slice(0, space).toLowerCase() === 'bearer'
        ? header.slice(space + 1)
        : '';
    const matched = matchApiKey(token, entries);
    if (matched === null) {
      return c.json(
        { error: { code: 'unauthorized', message: 'invalid or missing API key' } },
        401,
      );
    }
    if (matched.expiresAt !== null && Date.now() > matched.expiresAt) {
      return c.json(
        { error: { code: 'key_expired', message: 'API key has expired' } },
        401,
      );
    }
    c.set('authKeyId', keyFingerprint(matched.key));
    return next();
  };
}
